project:
  type: website
  output-dir: docs

website:
  title: "Longitudinal Analysis"
  favicon: "./figures/lights.png"
  twitter-card: true
  site-url: https://swhawes.github.io/test/
  page-navigation: true
  navbar:
    background: primary
    search: true
    pinned: true
    collapsed: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Manuscript"
        file: manuscript.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "How-To"
        file: howto.qmd
      - text: "Fundamentals"
        file: fundamentals.qmd
      - text: "Reference"
        file: reference.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/swhawes/test
          - text: Report a Bug
            url:  https://github.com/swhawes/test/issues

  sidebar:
    - title: "Manuscript"
      logo: "./figures/lights.png"
      pinned: true
      tools:
        - icon: twitter
          href: https://twitter.com
        - icon: github
          menu:
            - text: Source Code
              url:  https://github.com/swhawes/test
            - text: Report a Bug
              url:  https://github.com/swhawes/test/issues
      style: "docked"
      search: true
      background: light
      collapse-level: 1
      contents:
        - manuscript.qmd
    - title: "Tutorials"
      contents:
        - tutorials.qmd
        - section: "Traditional Linear Models"
          contents:
            - 1_Tutorials_DifferenceScores.qmd
            - 2_Tutorials_ResidualizedChangeScores.qmd
            - 3_Tutorials_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - 4_Tutorials_SignedRankTest.qmd
            - 5_Tutorials_MarginalModels.qmd
            - 6_Tutorials_GeneralizedEstimatingEquations.qmd
            - 7_Tutorials_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - 8_Tutorials_AutoregressiveCrosslaggedPanelModels.qmd
            - 9_Tutorials_LatentChangeScoresModels.qmd
            - 10_Tutorials_LatentGrowthCurveModels.qmd
            - 11_Tutorials_MultivariateLatentGrowthCurveModels.qmd
            - 12_Tutorials_LatentTransitionAnalysis.qmd
            - 13_Tutorials_GrowthMixtureModels.qmd
            - 14_Tutorials_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_Tutorials_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_Tutorials_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        
    - title: "How-To"
      contents:
        - section: "First Section"
          contents:
            - howto.qmd
        - section: "Second Section"
          contents:
            - 1a_Difference Scores paired samples ttest_HowTo.qmd
        # navigation items

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items

  page-footer:
    center:
      - text: "Longitudinal Analysis"
        href: refernce.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 1
    toc-expand: 3
    toc-title: Contentszz
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-fold: show
    code-summary: "Code"
    
#execute:
#  warning: false

execute:
  echo: true
  message: false
  warning: false
  error: false
  #comment: NA
  cache: true
  cold-folding: true
  R.options: list(width=220)
  fig.align: "center"
  out.width: "75%"
  fig.asp: .75
  dev: "cairo_pdf"

bibliography: references.bib

comments:
  hypothesis: true
# comments:
#   hypothesis: 
#     theme: clean
# comments:
#   utterances:
#     repo: quarto-dev/quarto-docs
# comments:
#   giscus: 
#     repo: quarto-dev/quarto-docs



