project:
  type: website
  output-dir: docs

website:
  title: "Longitudinal Analysis"
  favicon: "./figures/lights.png"
  twitter-card: true
  site-url: https://swhawes.github.io/test/
  page-navigation: true
  navbar:
    background: darkblue #slategray #primary #goldenrod
    search: true
    pinned: true
    collapsed: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Manuscript"
        file: manuscript.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "How-To"
        file: howto.qmd
      - text: "Explanations"
        file: explanations.qmd
      - text: "Reference"
        file: reference.qmd
      - text: "Documentation"
        file: documentation.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/swhawes/test
            #url:  "./tutorials.qmd"
          - text: Report a Bug
            url:  https://github.com/swhawes/test/issues

  sidebar:
    - title: "Manuscript"
      logo: "./figures/lights.png"
      pinned: true
      tools:
        - icon: twitter
          href: https://twitter.com
        - icon: github
          menu:
            - text: Source Code
              url:  https://github.com/swhawes/test
            - text: Report a Bug
              url:  https://github.com/swhawes/test/issues
      style: "docked"
      search: true
      background: light
      collapse-level: 1
      contents:
        - manuscript.qmd
    - title: "Tutorials"
      contents:
        - tutorials.qmd
        - section: "Traditional Linear Models"
          contents:
            - 1_Tutorials_DifferenceScores.qmd
            - 2_Tutorials_ResidualizedChangeScores.qmd
            - 3_Tutorials_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - 4_Tutorials_SignedRankTest.qmd
            - 5_Tutorials_MarginalModels.qmd
            - 6_Tutorials_GeneralizedEstimatingEquations.qmd
            - 7_Tutorials_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - 8_Tutorials_AutoregressiveCrosslaggedPanelModels.qmd
            - 9_Tutorials_LatentChangeScoresModels.qmd
            - 10_Tutorials_LatentGrowthCurveModels.qmd
            - 11_Tutorials_MultivariateLatentGrowthCurveModels.qmd
            - 12_Tutorials_LatentTransitionAnalysis.qmd
            - 13_Tutorials_GrowthMixtureModels.qmd
            - 14_Tutorials_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_Tutorials_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_Tutorials_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        - section: "Data Wrangling"
          contents:
            - blank.qmd
    - title: "How-To"
      contents:
        - howto.qmd
        - section: "Traditional Linear Models"
          contents:
            - section: "Difference Scores"
              contents:
                - 1a_HowTos_DifferenceScores_PairedTtests.qmd
                - 1b_HowTos_DifferenceScores_SimpleRegression.qmd
            - section: "Residualized Change Scores"
              contents:
                - 2_HowTos_ResidualizedChangeScores.qmd
            - section: "Linear Mixed Models"
              contents:
                - 3a_HowTos_LinearMixedModels.qmd
                - 3b_HowTos_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - section: "Signed-Rank Test"
              contents: 
                - 4_HowTos_SignedRankTest.qmd
            - section: "Marginal Models"
              contents:
                - 5_HowTos_MarginalModels.qmd
            - section: "Generalized Estimating Equations"
              contents:
                - 6_HowTos_GeneralizedEstimatingEquations.qmd
            - section: "Generalized Linear Mixed-Effects Models"
              contents:
                - 7_HowTos_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - section: "Autoregressive Crosslagged Panel Models"
              contents:
                - 8_HowTos_AutoregressiveCrosslaggedPanelModels.qmd
            - section: "Latent Change Scores Models"
              contents:
                - 9_HowTos_LatentChangeScoresModels.qmd
            - section: "LatentGrowthCurveModels"
              contents:
                - 10_HowTos_LatentGrowthCurveModels.qmd
            - section: "Multivariate Latent Growth Curve Models"
              contents:
                - 11_HowTos_MultivariateLatentGrowthCurveModels.qmd
            - section: "Latent Transition Analysis"
              contents:
                - 12_HowTos_LatentTransitionAnalysis.qmd
            - section: "Growth Mixture Models"
              contents:
                - 13_HowTos_GrowthMixtureModels.qmd
            - section: "State-Trait Models"
              contents:
                - 14_HowTos_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_HowTos_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_HowTos_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        - section: "Data Wrangling"
          contents:
            - blank.qmd
        # navigation items
    - title: "Explanations"
      contents:
        - explanations.qmd
        - section: "Traditional Linear Models"
          contents:
            - 1_Explanations_DifferenceScores.qmd
            - 2_Explanations_ResidualizedChangeScores.qmd
            - 3_Explanations_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - 4_Explanations_SignedRankTest.qmd
            - 5_Explanations_MarginalModels.qmd
            - 6_Explanations_GeneralizedEstimatingEquations.qmd
            - 7_Explanations_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - 8_Explanations_AutoregressiveCrosslaggedPanelModels.qmd
            - 9_Explanations_LatentChangeScoresModels.qmd
            - 10_Explanations_LatentGrowthCurveModels.qmd
            - 11_Explanations_MultivariateLatentGrowthCurveModels.qmd
            - 12_Explanations_LatentTransitionAnalysis.qmd
            - 13_Explanations_GrowthMixtureModels.qmd
            - 14_Explanations_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_Explanations_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_Explanations_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        - section: "Data Wrangling"
          contents:
            - blank.qmd
        # navigation items
  
    - title: "Reference"
      contents:
        - reference.qmd
        - section: "List of Reference Material"
          contents:
            - ListofReferences.qmd

    - title: "Documentation"
      contents:
        - documentation.qmd

  page-footer:
    center:
      - text: "Longitudinal Analysis"
        href: reference.qmd
format:
  html:
    theme:
      light: cosmos #flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 1
    toc-expand: 3
    toc-title: Table of Contents
    anchor-sections: true
    smooth-scroll: true
    #fontsize: 1.1em
    linestretch: 1.5
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-fold: show
    code-summary: "Code"
    code-overflow: scroll
    code-line-numbers: TRUE
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    html-math-method: katex
    df-print: paged
    options: max.print=75000
    grid:
     sidebar-width: 425px
    
execute:
  echo: true
  message: false
  warning: false
  error: false
  #comment: NA
  cache: true
  cold-folding: true
  R.options: list(width=220)
  fig.align: "center"
  out.width: "75%"
  fig.asp: .75
  dev: "cairo_pdf"

bibliography: references.bib

comments:
  hypothesis: true
# comments:
#   hypothesis: 
#     theme: clean
# comments:
#   utterances:
#     repo: quarto-dev/quarto-docs
# comments:
#   giscus: 
#     repo: quarto-dev/quarto-docs



