project:
  type: website
  output-dir: docs

website:
  title: "swhawes.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - 1a_Difference Scores paired samples ttest_HowTo.qmd
      - 2b_Residualized Change Score multiple regression_HowTo.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



